package phoebe.eqx.pcef.enums;

public enum EError {

    //Usage Monitoring
    USAGE_MONITORING_EXTRACT_ERROR("500000", "USAGE_MONITORING_EXTRACT_ERROR"),
    USAGE_MONITORING_MISSING_PARAMETER("500001", "USAGE_MONITORING_MISSING_PARAMETER"),
    USAGE_MONITORING_WRONG_FORMAT("500002", "USAGE_MONITORING_WRONG_FORMAT"),
    USAGE_MONITORING_BUILD_RESPONSE_ERROR("500003", "USAGE_MONITORING_BUILD_RESPONSE_ERROR"),

    //Refund Management
    REFUND_MANAGEMENT_EXTRACT_ERROR("500100", "REFUND_MANAGEMENT_EXTRACT_ERROR"),
    REFUND_MANAGEMENT_MISSING_PARAMETER("500101", "REFUND_MANAGEMENT_MISSING_PARAMETER"),
    REFUND_MANAGEMENT_WRONG_FORMAT("500102", "REFUND_MANAGEMENT_WRONG_FORMAT"),

    //GyRAR
    GYRAR_EXTRACT_ERROR("500200", "GYRAR_EXTRACT_ERROR"),
    GYRAR_MISSING_PARAMETER("500201", "GYRAR_MISSING_PARAMETER"),
    GYRAR_WRONG_FORMAT("500202", "GYRAR_WRONG_FORMAT"),

    //Usage Monitoring Start
    USAGE_MONITORING_START_BUILD_REQUEST_ERROR("500300", "USAGE_MONITORING_START_BUILD_REQUEST_ERROR"),
    USAGE_MONITORING_START_RESPONSE_TIMEOUT("500301", "USAGE_MONITORING_START_RESPONSE_TIMEOUT"),
    USAGE_MONITORING_START_RESPONSE_EQUINOX_ERROR("500302", "USAGE_MONITORING_START_RESPONSE_EQUINOX_ERROR"),
    USAGE_MONITORING_START_RESPONSE_EXTRACT_ERROR("500303", "USAGE_MONITORING_START_RESPONSE_EXTRACT_ERROR"),
    USAGE_MONITORING_START_RESPONSE_MISSING_PARAMETER("500304", "USAGE_MONITORING_START_RESPONSE_MISSING_PARAMETER"),
    USAGE_MONITORING_START_RESPONSE_WRONG_FORMAT("500305", "USAGE_MONITORING_START_RESPONSE_WRONG_FORMAT"),
    USAGE_MONITORING_START_RESPONSE_ERROR("500306", "USAGE_MONITORING_START_RESPONSE_ERROR"),
    USAGE_MONITORING_START_RESPONSE_NOT_IMPLEMENT("500307", "USAGE_MONITORING_START_RESPONSE_NOT_IMPLEMENT"),

    //Usage Monitoring Update
    USAGE_MONITORING_UPDATE_BUILD_REQUEST_ERROR("500400", "USAGE_MONITORING_UPDATE_BUILD_REQUEST_ERROR"),
    USAGE_MONITORING_UPDATE_RESPONSE_TIMEOUT("500401", "USAGE_MONITORING_UPDATE_RESPONSE_TIMEOUT"),
    USAGE_MONITORING_UPDATE_RESPONSE_EQUINOX_ERROR("500402", "USAGE_MONITORING_UPDATE_RESPONSE_EQUINOX_ERROR"),
    USAGE_MONITORING_UPDATE_RESPONSE_EXTRACT_ERROR("500403", "USAGE_MONITORING_UPDATE_RESPONSE_EXTRACT_ERROR"),
    USAGE_MONITORING_UPDATE_RESPONSE_MISSING_PARAMETER("500404", "USAGE_MONITORING_UPDATE_RESPONSE_MISSING_PARAMETER"),
    USAGE_MONITORING_UPDATE_RESPONSE_WRONG_FORMAT("500405", "USAGE_MONITORING_UPDATE_RESPONSE_WRONG_FORMAT"),
    USAGE_MONITORING_UPDATE_RESPONSE_ERROR("500406", "USAGE_MONITORING_UPDATE_RESPONSE_ERROR"),
    USAGE_MONITORING_UPDATE_RESPONSE_NOT_IMPLEMENT("500407", "USAGE_MONITORING_UPDATE_RESPONSE_NOT_IMPLEMENT"),

    //Usage Monitoring Stop
    USAGE_MONITORING_STOP_BUILD_REQUEST_ERROR("500500", "USAGE_MONITORING_STOP_BUILD_REQUEST_ERROR"),
    USAGE_MONITORING_STOP_RESPONSE_TIMEOUT("500501", "USAGE_MONITORING_STOP_RESPONSE_TIMEOUT"),
    USAGE_MONITORING_STOP_RESPONSE_EQUINOX_ERROR("500502", "USAGE_MONITORING_STOP_RESPONSE_EQUINOX_ERROR"),
    USAGE_MONITORING_STOP_RESPONSE_EXTRACT_ERROR("500503", "USAGE_MONITORING_STOP_RESPONSE_EXTRACT_ERROR"),
    USAGE_MONITORING_STOP_RESPONSE_MISSING_PARAMETER("500504", "USAGE_MONITORING_STOP_RESPONSE_MISSING_PARAMETER"),
    USAGE_MONITORING_STOP_RESPONSE_WRONG_FORMAT("500505", "USAGE_MONITORING_STOP_RESPONSE_WRONG_FORMAT"),
    USAGE_MONITORING_STOP_RESPONSE_NOT_IMPLEMENT("500506", "USAGE_MONITORING_STOP_RESPONSE_NOT_IMPLEMENT"),

    //Refund Transaction
    REFUND_TRANSACTION_BUILD_REQUEST_ERROR("500600", "REFUND_TRANSACTION_BUILD_REQUEST_ERROR"),
    REFUND_TRANSACTION_RESPONSE_TIMEOUT("500601", "REFUND_TRANSACTION_RESPONSE_TIMEOUT"),
    REFUND_TRANSACTION_RESPONSE_EQUINOX_ERROR("500602", "REFUND_TRANSACTION_RESPONSE_EQUINOX_ERROR"),
    REFUND_TRANSACTION_RESPONSE_EXTRACT_ERROR("500603", "REFUND_TRANSACTION_RESPONSE_EXTRACT_ERROR"),
    REFUND_TRANSACTION_RESPONSE_MISSING_PARAMETER("500604", "REFUND_TRANSACTION_RESPONSE_MISSING_PARAMETER"),
    REFUND_TRANSACTION_RESPONSE_WRONG_FORMAT("500605", "REFUND_TRANSACTION_RESPONSE_WRONG_FORMAT"),
    REFUND_TRANSACTION_RESPONSE_ERROR("500606", "REFUND_TRANSACTION_RESPONSE_ERROR"),

    //Get Product
    GET_PRODUCT_BUILD_REQUEST_ERROR("500700", "GET_PRODUCT_BUILD_REQUEST_ERROR"),
    GET_PRODUCT_RESPONSE_TIMEOUT("500701", "GET_PRODUCT_RESPONSE_TIMEOUT"),
    GET_PRODUCT_RESPONSE_EQUINOX_ERROR("500702", "GET_PRODUCT_RESPONSE_EQUINOX_ERROR"),
    GET_PRODUCT_RESPONSE_EXTRACT_ERROR("500703", "GET_PRODUCT_RESPONSE_EXTRACT_ERROR"),
    GET_PRODUCT_RESPONSE_MISSING_PARAMETER("500704", "GET_PRODUCT_RESPONSE_MISSING_PARAMETER"),
    GET_PRODUCT_RESPONSE_WRONG_FORMAT("500705", "GET_PRODUCT_RESPONSE_WRONG_FORMAT"),
    GET_PRODUCT_RESPONSE_DATA_NOT_FOUND("500706", "GET_PRODUCT_RESPONSE_DATA_NOT_FOUND"),
    GET_PRODUCT_RESPONSE_INVALID_DATA("500707", "GET_PRODUCT_RESPONSE_INVALID_DATA"),
    GET_PRODUCT_RESPONSE_UNAUTHORIZED("500708", "GET_PRODUCT_RESPONSE_UNAUTHORIZED"),
    GET_PRODUCT_RESPONSE_FORBIDDEN("500709", "GET_PRODUCT_RESPONSE_FORBIDDEN"),
    GET_PRODUCT_RESPONSE_NOT_FOUND("500710", "GET_PRODUCT_RESPONSE_NOT_FOUND"),
    GET_PRODUCT_RESPONSE_ERROR("500711", "GET_PRODUCT_RESPONSE_FORBIDDEN"),

    //Collection Transaction
    INSERT_TRANSACTION_BUILD_ERROR("500800", "INSERT_TRANSACTION_BUILD_ERROR"),
    INSERT_TRANSACTION_RESPONSE_TIMEOUT("500801", "INSERT_TRANSACTION_RESPONSE_TIMEOUT"),
    INSERT_TRANSACTION_RESPONSE_ERROR("500802", "INSERT_TRANSACTION_RESPONSE_ERROR"),
    INSERT_TRANSACTION_RESPONSE_DUPPLICATE_KEY("500803", "INSERT_TRANSACTION_RESPONSE_DUPPLICATE_KEY"),
    READ_TRANSACTION_BUILD_REQUEST_ERROR("500804", "READ_TRANSACTION_BUILD_REQUEST_ERROR"),
    READ_TRANSACTION_RESPONSE_TIMEOUT("500805", "READ_TRANSACTION_RESPONSE_TIMEOUT"),
    READ_TRANSACTION_RESPONSE_ERROR("500806", "READ_TRANSACTION_RESPONSE_ERROR"),
    READ_TRANSACTION_RESPONSE_NOT_FOUND("500807", "READ_TRANSACTION_RESPONSE_NOT_FOUND"),
    UPDATE_TRANSACTION_REQUEST_ERROR("500808", "UPDATE_TRANSACTION_REQUEST_ERROR"),
    UPDATE_TRANSACTION_RESPONSE_TIMEOUT("500809", "UPDATE_TRANSACTION_RESPONSE_TIMEOUT"),
    UPDATE_TRANSACTION_RESPONSE_ERROR("500810", "UPDATE_TRANSACTION_RESPONSE_ERROR"),
    DELETE_TRANSACTION_REQUEST_ERROR("500811", "DELETE_TRANSACTION_REQUEST_ERROR"),
    DELETE_TRANSACTION_RESPONSE_TIMEOUT("500812", "DELETE_TRANSACTION_RESPONSE_TIMEOUT"),
    DELETE_TRANSACTION_RESPONSE_ERROR("500813", "DELETE_TRANSACTION_RESPONSE_ERROR"),

    //Collection Profile
    INSERT_PROFILE_BUILD_ERROR("500900", "INSERT_PROFILE_BUILD_ERROR"),
    INSERT_PROFILE_RESPONSE_TIMEOUT("500901", "INSERT_PROFILE_RESPONSE_TIMEOUT"),
    INSERT_PROFILE_RESPONSE_ERROR("500902", "INSERT_PROFILE_RESPONSE_ERROR"),
    INSERT_PROFILE_RESPONSE_DUPPLICATE_KEY("500903", "INSERT_PROFILE_RESPONSE_DUPPLICATE_KEY"),
    READ_PROFILE_BUILD_REQUEST_ERROR("500904", "READ_PROFILE_BUILD_REQUEST_ERROR"),
    READ_PROFILE_RESPONSE_TIMEOUT("500905", "READ_PROFILE_RESPONSE_TIMEOUT"),
    READ_PROFILE_RESPONSE_ERROR("500906", "READ_PROFILE_RESPONSE_ERROR"),
    READ_PROFILE_RESPONSE_NOT_FOUND("500907", "READ_PROFILE_RESPONSE_NOT_FOUND"),
    UPDATE_PROFILE_REQUEST_ERROR("500908", "UPDATE_PROFILE_REQUEST_ERROR"),
    UPDATE_PROFILE_RESPONSE_TIMEOUT("500909", "UPDATE_PROFILE_RESPONSE_TIMEOUT"),
    UPDATE_PROFILE_RESPONSE_ERROR("500910", "UPDATE_PROFILE_RESPONSE_ERROR"),
    DELETE_PROFILE_REQUEST_ERROR("500911", "DELETE_PROFILE_REQUEST_ERROR"),
    DELETE_PROFILE_RESPONSE_TIMEOUT("500912", "DELETE_PROFILE_RESPONSE_TIMEOUT"),
    DELETE_PROFILE_RESPONSE_ERROR("500913", "DELETE_PROFILE_RESPONSE_ERROR"),

    //Collection Quota
    INSERT_QUOTA_BUILD_ERROR("501000", "INSERT_QUOTA_BUILD_ERROR"),
    INSERT_QUOTA_RESPONSE_TIMEOUT("501001", "INSERT_QUOTA_RESPONSE_TIMEOUT"),
    INSERT_QUOTA_RESPONSE_ERROR("501002", "INSERT_QUOTA_RESPONSE_ERROR"),
    INSERT_QUOTA_RESPONSE_DUPPLICATE_KEY("501003", "INSERT_QUOTA_RESPONSE_DUPPLICATE_KEY"),
    READ_QUOTA_BUILD_REQUEST_ERROR("501004", "READ_QUOTA_BUILD_REQUEST_ERROR"),
    READ_QUOTA_RESPONSE_TIMEOUT("501005", "READ_QUOTA_RESPONSE_TIMEOUT"),
    READ_QUOTA_RESPONSE_ERROR("501006", "READ_QUOTA_RESPONSE_ERROR"),
    READ_QUOTA_RESPONSE_NOT_FOUND("501007", "READ_QUOTA_RESPONSE_NOT_FOUND"),
    UPDATE_QUOTA_REQUEST_ERROR("501008", "UPDATE_QUOTA_REQUEST_ERROR"),
    UPDATE_QUOTA_RESPONSE_TIMEOUT("501009", "UPDATE_QUOTA_RESPONSE_TIMEOUT"),
    UPDATE_QUOTA_RESPONSE_ERROR("501010", "UPDATE_QUOTA_RESPONSE_ERROR"),
    DELETE_QUOTA_REQUEST_ERROR("501011", "DELETE_QUOTA_REQUEST_ERROR"),
    DELETE_QUOTA_RESPONSE_TIMEOUT("501012", "DELETE_QUOTA_RESPONSE_TIMEOUT"),
    DELETE_QUOTA_RESPONSE_ERROR("501013", "DELETE_QUOTA_RESPONSE_ERROR"),

    //Other
    Other("999999", "Other"),

    ;


    private String code;
    private String desc;

    EError(String code, String desc) {
        this.code = code;
        this.desc = desc;
    }

    public String getCode() {
        return code;
    }

    public String getDesc() {
        return desc;
    }
}
