package phoebe.eqx.pcef.enums.state;

public enum EMongoState {
    BEGIN,
    CHECK_QUOTA_AVAILIABLE,
    FIND_AND_MOD_PROFILE_FOR_UPDATE_QUOTA_EXHAUST,
    FIND_AND_MOD_PROFILE_FOR_WAIT_PROCESS,
    REMOVE_QUOTA_GYRAR,
    FIND_AND_MOD_QUOTA_FOR_WAIT_PROCESS,
    USAGE_REPORT,
    INSERT_PROFILE,
    FIND_QUOTA_EXPIRE,
    FIND_USAGE_RESOURCE,
    REFUND_STATUS_DONE,
    REFUND_STATUS_COMPLETED,


    END;
}
